// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Reportex.Models
{
    public partial class Reporte
    {
        public Reporte()
        {
            RolReporte = new HashSet<RolReporte>();
        }

        public int ReporteId { get; set; }
        public string Denominacion { get; set; }
        public string url { get; set; }
        public string estado { get; set; }

        public virtual ICollection<RolReporte> RolReporte { get; set; }
    }
}