// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Reportex.Models
{
    public partial class RolMenu
    {
        public int RolMenuId { get; set; }
        public int? RolId { get; set; }
        public int? MenuId { get; set; }

        public virtual Menu Menu { get; set; }
        public virtual Rol Rol { get; set; }
    }
}