// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Reportex.Models
{
    public partial class RolReporte
    {
        public int RolReporteId { get; set; }
        public int? RolId { get; set; }
        public int? ReporteId { get; set; }

        public virtual Reporte Reporte { get; set; }
        public virtual Rol Rol { get; set; }
    }
}