// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Reportex.Models
{
    public partial class UsuarioRol
    {
        public int UsuarioRolId { get; set; }
        public int? UsuarioId { get; set; }
        public int? RolId { get; set; }

        public virtual Rol Rol { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}